version: '3'
services:
  php-api:
    build:
      context: . # The current directory where Dockerfile is located
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    volumes:
      - ./api.php:/var/www/html/api.php # Mount the PHP script
      - ./services.csv:/var/www/html/services.csv # Mount the CSV file
